// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

import { line, curveMonotoneX, curveLinear } from "d3-shape";
import { AbstractChart, AbstractChartOptions } from "~/component/chart/AbstractChart.js";
import { linearScale, timeScale, pointsXExtent, pointsYBounds } from "~/component/chart/Scale.js";
import type { ChartScale } from "~/component/chart/Scale.js";
import { callable } from "~/core/Callable.js";
import type { ChartPoint, PlotRect } from "~/component/chart/types.js";

/** The x-axis scale kind a line chart uses. */
export type LineChartScaleType = "linear" | "time";

/**
 * Construction-time options for {@link LineChart}.
 *
 * @category Components
 */
export interface LineChartOptions extends AbstractChartOptions {
    /** Whether to draw a circle marker at each point; defaults to `true`. */
    showPoints?: boolean;
    /** Whether to smooth the line (monotone curve) vs straight segments; defaults to `false`. */
    curved?: boolean;
    /** The x-axis scale kind; defaults to `"linear"`. */
    xScaleType?: LineChartScaleType;
}

/**
 * A line chart: one path per series over a linear or time x axis and a linear y
 * axis, with optional point markers. The path `d` string is generated by the
 * pure `d3-shape` `line()` generator (optionally with a monotone curve) and fed
 * straight into a `setAttr({ d })` through the sink — no DOM-owning d3 code.
 *
 * @category Components
 */
class LineChart extends AbstractChart<LineChartOptions> {

    /**
     * Builds the line chart, then dispatches its own options from the
     * constructor body (after `super()` has wired the base chart).
     *
     * @param options - Optional construction-time options.
     */
    constructor(options?: LineChartOptions) {
        super(options);

        this.dispatchLineOptions(options);
    }

    /**
     * Dispatches the line-specific options through their setters.
     *
     * @param options - The construction options, or `undefined`.
     */
    private dispatchLineOptions(options?: LineChartOptions): void {
        if (!options) {
            return;
        }

        if (options.showPoints !== undefined) {
            this.setShowPoints(options.showPoints);
        }

        if (options.curved !== undefined) {
            this.setCurved(options.curved);
        }

        if (options.xScaleType !== undefined) {
            this.setXScaleType(options.xScaleType);
        }
    }

    /**
     * Sets whether point markers are drawn and repaints.
     *
     * @param value - `true` to draw circle markers at each point.
     *
     * @returns This chart, for method chaining.
     */
    setShowPoints(value: boolean): this {
        this._options.showPoints = value;

        this.scheduleLayout();

        return this;
    }

    /**
     * Returns whether point markers are drawn (defaults to `true`).
     *
     * @returns `true` when markers are drawn.
     */
    isShowPoints(): boolean {
        return this._options.showPoints ?? true;
    }

    /**
     * Sets whether the line is smoothed (monotone curve) and repaints.
     *
     * @param value - `true` to smooth the line.
     *
     * @returns This chart, for method chaining.
     */
    setCurved(value: boolean): this {
        this._options.curved = value;

        this.scheduleLayout();

        return this;
    }

    /**
     * Returns whether the line is smoothed (defaults to `false`).
     *
     * @returns `true` when smoothed.
     */
    isCurved(): boolean {
        return this._options.curved ?? false;
    }

    /**
     * Sets the x-axis scale kind and repaints.
     *
     * @param value - The scale kind.
     *
     * @returns This chart, for method chaining.
     */
    setXScaleType(value: LineChartScaleType): this {
        this._options.xScaleType = value;

        this.scheduleLayout();

        return this;
    }

    /**
     * Returns the x-axis scale kind (defaults to `"linear"`).
     *
     * @returns The scale kind.
     */
    getXScaleType(): LineChartScaleType {
        return this._options.xScaleType ?? "linear";
    }

    /**
     * Flattens the points of every visible series into one array (for domain
     * computation).
     *
     * @returns The visible points.
     */
    private visiblePoints(): ChartPoint[] {
        return this._series.filter((m) => !m.hidden).flatMap((m) => m.points);
    }

    /**
     * Builds a linear or time x scale and a linear y scale against the plot
     * rectangle, from the visible points' extents.
     *
     * @param plot - The plot rectangle.
     *
     * @returns The x and y scales.
     */
    protected buildScales(plot: PlotRect): { x: ChartScale; y: ChartScale } {
        const points = this.visiblePoints();
        const [xMin, xMax] = pointsXExtent(points);
        const yBounds = pointsYBounds(points);
        const xRange: [number, number] = [plot.x, plot.x + plot.width];
        const yRange: [number, number] = [plot.y + plot.height, plot.y];

        const x = this.getXScaleType() === "time"
            ? timeScale([new Date(xMin), new Date(xMax)], xRange)
            : linearScale([xMin, xMax], xRange);

        return { x, y: linearScale(yBounds, yRange) };
    }

    /**
     * Draws one path per visible series (plus optional point markers), tagging
     * each mark with its `data-series` / `data-index` and binding its colour to
     * the palette. The path `d` comes from `d3-shape`'s `line()` generator.
     *
     * @param plot - The plot rectangle (unused; the scales carry the geometry).
     * @param xScale - The x scale.
     * @param yScale - The y scale.
     */
    protected drawSeries(_plot: PlotRect, xScale: ChartScale, yScale: ChartScale): void {
        const project = this.projector(xScale, yScale);
        const curve = this.isCurved() ? curveMonotoneX : curveLinear;

        this._series.forEach((model, seriesIndex) => {
            if (model.hidden) {
                return;
            }

            const color = this.seriesColor(seriesIndex, model);
            const path = line<ChartPoint>().x((p) => project.x(p.x)).y((p) => project.y(p.y)).curve(curve)(model.points);

            // The path spans the whole series, so it carries `data-series` only
            // (no per-point `data-index`): hovering the line shows a series-level
            // tooltip, while per-point hover/selection rides on the point markers
            // below. With `showPoints: false` the line stays series-level hoverable.
            this.seriesMark("path", {
                setAttr: { d: path ?? "", "data-series": String(seriesIndex) },
                style:   { fill: "none", stroke: color, "stroke-width": "var(--ts-ui-chart-line-width)" },
            });

            if (this.isShowPoints()) {
                this.drawPoints(model.points, seriesIndex, color, project);
            }
        });
    }

    /**
     * Draws a circle marker per point, each hit-taggable via its
     * `data-series` / `data-index`.
     *
     * @param points - The series points.
     * @param seriesIndex - The series index.
     * @param color - The resolved series colour.
     * @param project - The point→pixel projectors.
     */
    private drawPoints(points: ChartPoint[], seriesIndex: number, color: string, project: { x: (v: number) => number; y: (v: number) => number }): void {
        points.forEach((point, index) => {
            this.seriesMark("circle", {
                setAttr: { cx: String(project.x(point.x)), cy: String(project.y(point.y)), r: "var(--ts-ui-chart-point-radius)", "data-series": String(seriesIndex), "data-index": String(index) },
                style:   { fill: color },
            });
        });
    }

    /**
     * Returns the pixel anchor of a datum for the selection ring.
     *
     * @param plot - The plot rectangle (unused).
     * @param xScale - The x scale.
     * @param yScale - The y scale.
     * @param series - The datum's series index.
     * @param index - The datum's index within its series.
     *
     * @returns The pixel anchor, or `null` when out of range.
     */
    protected pointPixel(_plot: PlotRect, xScale: ChartScale, yScale: ChartScale, series: number, index: number): { x: number; y: number } | null {
        const point = this._series[series]?.points[index];

        if (!point) {
            return null;
        }

        const project = this.projector(xScale, yScale);

        return { x: project.x(point.x), y: project.y(point.y) };
    }

    /**
     * Adapts the continuous x/y scales into plain numeric projectors. The line
     * chart's x scale is always continuous (linear/time), so the band-scale arm
     * of the {@link ChartScale} union never applies here.
     *
     * @param xScale - The x scale.
     * @param yScale - The y scale.
     *
     * @returns The `x` and `y` value→pixel projectors.
     */
    private projector(xScale: ChartScale, yScale: ChartScale): { x: (v: number) => number; y: (v: number) => number } {
        return {
            x: xScale as unknown as (v: number) => number,
            y: yScale as unknown as (v: number) => number,
        };
    }
}

const LineChartCallable = callable(LineChart);
type LineChartCallable = LineChart;
export {
    LineChart         as _LineChart,
    LineChartCallable as LineChart
};
